version: "3"
services:

  nginx:
    image: nginx:1.15
    ports:
      - 8000:8000
    depends_on:
      - app
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./scripts/dev/Dockerfile
    environment:
      - APP_PORT=8000
      - APP_VERSION=local
      - DB_NAME=exam2022
      - DB_USERNAME=sa
      - DB_PASSWORD=Sa1angXD
      - DB_HOST=10.116.17.130
      - DB_PORT=1433
      - STAGE=dev
      - ELS_URL=http://10.116.17.130:9200
      - ELS_USERNAME=elastic
      - ELS_PASSWORD=changeme
      - ELS_INDEX=test-login
    volumes:
      - ./src:/go/src/app/src
      - ./apidocs:/go/src/app/apidocs
      - ./assets:/go/src/app/assets